server:
  port: 8080

client:
  stocks.url: http://localhost:8082
  prices.url: http://localhost:8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:publicKey.pem
          