version: 1
task_definition:
  task_execution_role: ecsTaskExecutionRole
  ecs_network_mode: awsvpc
  task_size:
    mem_limit: 0.5GB
    cpu_limit: 256
run_params:
  network_configuration:
    awsvpc_configuration:
      subnets:
        - "subnet-0449347227d14d272"
        - "subnet-0057ae8968a04a500"
      security_groups:
        - "sg-0c941edb775c0e802"
      assign_public_ip: ENABLED
