AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Quarkus HTTP - nl.zencode::portfolio-q-stock
Globals:
  Api:
    EndpointConfiguration: REGIONAL
    BinaryMediaTypes:
    - '*/*'
Resources:
  PortfolioQStockNativeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: not.used.in.provided.runtimei
      Runtime: provided
      CodeUri: s3://portfolio-stock/c78d47552e57318c88e2cb8882a782a7
      MemorySize: 128
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 15
      Environment:
        Variables:
          DISABLE_SIGNAL_HANDLERS: true
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
Outputs:
  PortfolioQStockNativeApi:
    Description: URL for application
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
    Export:
      Name: PortfolioQStockNativeApi
